### PR TITLE
Bringing in GUI 

### PR DESCRIPTION
**Pull request by awalter-bnl**
Add GUI functionality.

(This supersedes #15 after horrendous git workflow problems)

### CODE REVIEW

**Comment by awalter-bnl** [comment]
Just noticed that this specifies that I opened this. For the record (not meaning to steel anyones thunder) it was actually @mpmdean while at my computer !-)

**Comment by mpmdean** [comment]
Sure

**Comment by mpmdean** [comment]
Not sure it's a thunderous pull request but thanks!

**Comment by mpmdean** [comment]
Perhaps we can just merge this? I don't envisage anyone else looking at this.

**Comment by danielballan** [comment]
Yeah, GUI code is hard to review. :+1: for merging.

**Pull request merged**
